In [1]:
import pandas as pd

In [ ]:
serie = pd.Series([101, 24, 32, 3, 312])
serie

0      1
1      2
2     32
3      3
4    312
dtype: int64

In [4]:
serie[serie > 100]

4    312
dtype: int64

In [5]:
serie.describe()

count      5.000000
mean      70.000000
std      135.906218
min        1.000000
25%        2.000000
50%        3.000000
75%       32.000000
max      312.000000
dtype: float64

In [7]:
df = pd.DataFrame([101, 24, 32, 3, 312])
df

     0
0  101
1   24
2   32
3    3
4  312

In [8]:
df.describe()

                0
count    5.000000
mean    94.400000
std    127.079896
min      3.000000
25%     24.000000
50%     32.000000
75%    101.000000
max    312.000000

In [10]:
df = pd.DataFrame([101, 24, 32, 3, 312], columns=["Masuratori"])
df

   Masuratori
0         101
1          24
2          32
3           3
4         312

In [15]:
df = pd.DataFrame([[101, 24, 32, 3, 312], [32, 3, 312, 32, 32]], columns=["col1", "col2", "col3", "col4", "col5"])
df

   col1  col2  col3  col4  col5
0   101    24    32     3   312
1    32     3   312    32    32

In [16]:
df = pd.DataFrame({
    "Temperaturi" : [20, 21, 24],
    "Umiditate" : [50, 60, 70]

})
df

   Temperaturi  Umiditate
0           20         50
1           21         60
2           24         70

In [18]:
type(df["Temperaturi"])

pandas.core.series.Series

In [19]:
df["Temperaturi"]

0    20
1    21
2    24
Name: Temperaturi, dtype: int64

In [20]:
df.describe()

       Temperaturi  Umiditate
count     3.000000        3.0
mean     21.666667       60.0
std       2.081666       10.0
min      20.000000       50.0
25%      20.500000       55.0
50%      21.000000       60.0
75%      22.500000       65.0
max      24.000000       70.0

In [21]:
df.to_csv("data.csv")

In [22]:
df.to_json("data.json")

In [23]:
df.to_excel("data.xlsx")