In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/sojog/Python-ADR-6-9-februarie/refs/heads/main/clwin.csv", index_col="id")
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [5]:
df.iloc[17]

country     Romania
team           FCSB
trophies        NaN
Name: 17, dtype: object

In [12]:
df.iloc[17] = ["Romania", "Steaua", 1]

In [13]:
df.iloc[17]

country     Romania
team         Steaua
trophies        1.0
Name: 17, dtype: object

In [14]:
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania         Steaua       1.0
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [16]:
df.iloc[5]

country     England
team        Chelsea
trophies        2.0
Name: 5, dtype: object

In [19]:
df = df.drop_duplicates()
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania         Steaua       1.0
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
df

        country           team  trophies
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England   Nottm Forest       2.0
6      Portugal        Benfica       2.0
7         Italy       Juventus       2.0
8      Portugal       FC Porto       2.0
9       England       Man City       1.0
10      Germany       Dortmund       1.0
11  Netherlands      Feyenoord       1.0
12       France      Marseille       1.0
13      England    Aston Villa       1.0
14      Germany        Hamburg       1.0
15       Serbia  Crvena zvezda       1.0
16      Romania         Steaua       1.0
17  Netherlands            PSV       1.0
18     Scotland         Celtic       1.0

In [27]:
new_df = pd.DataFrame({
    "country" : ["Spain", "Italy"],
    "team" : ["Real Madrid", "Milan"],
    "trophies" : [15, 7]
})
new_df

  country         team  trophies
0   Spain  Real Madrid        15
1   Italy        Milan         7

In [31]:
concat_df = pd.concat([df, new_df])
concat_df

        country           team  trophies
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England   Nottm Forest       2.0
6      Portugal        Benfica       2.0
7         Italy       Juventus       2.0
8      Portugal       FC Porto       2.0
9       England       Man City       1.0
10      Germany       Dortmund       1.0
11  Netherlands      Feyenoord       1.0
12       France      Marseille       1.0
13      England    Aston Villa       1.0
14      Germany        Hamburg       1.0
15       Serbia  Crvena zvezda       1.0
16      Romania         Steaua       1.0
17  Netherlands            PSV       1.0
18     Scotland         Celtic       1.0
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0

In [34]:
merged_df = concat_df.sort_values("trophies", ascending=False).reset_index(drop=True)
merged_df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3         Spain      Barcelona       5.0
4         Italy          Inter       3.0
5       England     Man United       3.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England        Chelsea       2.0
11       Serbia  Crvena zvezda       1.0
12     Scotland         Celtic       1.0
13  Netherlands            PSV       1.0
14      Romania         Steaua       1.0
15       France      Marseille       1.0
16      Germany        Hamburg       1.0
17      England    Aston Villa       1.0
18  Netherlands      Feyenoord       1.0
19      England       Man City       1.0
20      Germany       Dortmund       1.0

In [38]:
merged_df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3         Spain      Barcelona       5.0
4         Italy          Inter       3.0
5       England     Man United       3.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England        Chelsea       2.0
11       Serbia  Crvena zvezda       1.0
12     Scotland         Celtic       1.0
13  Netherlands            PSV       1.0
14      Romania         Steaua       1.0
15       France      Marseille       1.0
16      Germany        Hamburg       1.0
17      England    Aston Villa       1.0
18  Netherlands      Feyenoord       1.0
19      England       Man City       1.0
20      Germany       Dortmund       1.0

In [40]:
merged_df.loc[21] = ["France", "PSG", 1]

In [41]:
merged_df

        country           team  trophies
0         Spain    Real Madrid      15.0
1         Italy          Milan       7.0
2       England      Liverpool       6.0
3         Spain      Barcelona       5.0
4         Italy          Inter       3.0
5       England     Man United       3.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England        Chelsea       2.0
11       Serbia  Crvena zvezda       1.0
12     Scotland         Celtic       1.0
13  Netherlands            PSV       1.0
14      Romania         Steaua       1.0
15       France      Marseille       1.0
16      Germany        Hamburg       1.0
17      England    Aston Villa       1.0
18  Netherlands      Feyenoord       1.0
19      England       Man City       1.0
20      Germany       Dortmund       1.0
21       France            PSG       1.0